# This Dockerfile is for rockstarapi folder abd multi-platform builds
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/nightly/sdk:10.0-preview AS build
ARG TARGETARCH
WORKDIR /source

# Copy project file and restore as distinct layers
COPY --link rockstarapi/*.csproj .
RUN dotnet restore -a $TARGETARCH

# Copy source code and publish app
COPY --link rockstarapi/. .
RUN dotnet publish -a $TARGETARCH --no-restore -o /app


# Runtime stage
FROM mcr.microsoft.com/dotnet/nightly/aspnet:10.0-preview
EXPOSE 8080
WORKDIR /app
COPY --link --from=build /app .
USER $APP_UID
ENTRYPOINT ["./rockstarapi"]
